version: '3.8'

services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/code
      - ${PIP_CACHE_DIR_DEV:-cache-dev}:/root/.cache
    ports:
      - "8000:8000"
    tty: true

volumes:
  cache-dev: